/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-08-02 06:27:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Personal Portfolio Website</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"./img/glogo.jpeg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\"\r\n");
      out.write("        integrity=\"sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>\r\n");
      out.write("    <script src='https://cdn.jsdelivr.net/npm/jquery.ripples@0.6.3/dist/jquery.ripples.min.js'></script> -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"> </script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.ripples/0.5.3/jquery.ripples.min.js\"> </script>\r\n");
      out.write("    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>\r\n");
      out.write("        <script src='https://cdn.jsdelivr.net/npm/jquery.ripples@0.6.3/dist/jquery.ripples.min.js'></script> -->\r\n");
      out.write("   <script src=\"/My_Portfolio/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"jquery-3.6.4.min.js\"></script>\r\n");
      out.write("    <script src=\"https://smtpjs.com/v3/smtp.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"scroll-up-btn\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <div class=\"logo\"><a href=\"#\">Port<span>folio.</span></a></div>\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("                <li><a href=\"#home\" class=\"menu-btn\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#about\" class=\"menu-btn\">About</a></li>\r\n");
      out.write("                <li><a href=\"#skills\" class=\"menu-btn\">Skills</a></li>\r\n");
      out.write("                <li><a href=\"#project\" class=\"menu-btn\">Project</a></li>\r\n");
      out.write("                <li><a href=\"#contact\" class=\"menu-btn\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"menu-btn\">\r\n");
      out.write("                <i class=\"fas fa-bars\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- home section start -->\r\n");
      out.write("    <section class=\"home\" id=\"home\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <div class=\"home-content\">\r\n");
      out.write("                <div class=\"text-1\">Hello, My name is</div>\r\n");
      out.write("                <div class=\"text-2\">Purva Warke</div>\r\n");
      out.write("                <div class=\"text-3\">And I'm a <span class=\"typing\"></span></div>\r\n");
      out.write("                <a href=\"./img/PURVA_WARKE_RESUME.pdf\" target=\"_blank\">Hire me</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- about section start -->\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <h2 class=\"title\">About me</h2>\r\n");
      out.write("            <div class=\"about-content\">\r\n");
      out.write("                <div class=\"column left\">\r\n");
      out.write("                    <img src=\"./img/Purva1.jpg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"column right\">\r\n");
      out.write("                    <div class=\"text\">I'm Purva and I'm a <span class=\"typing-2\"></span></div>\r\n");
      out.write("                    <p>Hello I'm Recently Post-Graduate (MCA-2023) Student with a passion for creating dynamic and\r\n");
      out.write("                        responsive websites.As a\r\n");
      out.write("                        web developer student with a background in computer applications, I am passionate about building\r\n");
      out.write("                        engaging and user-friendly websites. I have experience with HTML, CSS, JavaScript. I am\r\n");
      out.write("                        constantly learning and experimenting with new technologies to stay up-to-date with the latest\r\n");
      out.write("                        industry trends.</p>\r\n");
      out.write("                    <a href=\"./img/PURVA_WARKE_RESUME.pdf\" target=\"_blank\">Download CV</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- skills section start -->\r\n");
      out.write("    <section class=\"skills\" id=\"skills\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <h2 class=\"title\">My skills</h2>\r\n");
      out.write("            <div class=\"skills-content\">\r\n");
      out.write("                <div class=\"column left\">\r\n");
      out.write("                    <div class=\"text\">My creative skills & experiences.</div>\r\n");
      out.write("                    <p>Proficiency in programming languages: A web developer should be proficient in the programming\r\n");
      out.write("                        languages used to build web applications, such as HTML, CSS, JavaScript.\r\n");
      out.write("                        Web developers work in teams, so the ability to collaborate with designers, project managers,\r\n");
      out.write("                        and other developers is important. Good communication skills and the ability to work well in a\r\n");
      out.write("                        team environment are essential\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <!-- <a href=\"#\">Read more</a> -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"column right\">\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>HTML/CSS</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 70%\">70%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>JAVASCRIPT</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 50%\">50%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>Bootstrap</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 50%\">50%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>JAVA</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 60%\">60%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>JDBC / JSP</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 50%\">50%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>MYSQL(DATABASE)</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 80%\">80%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bars\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <span>C/C++</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"progress\" role=\"progressbar\" aria-label=\"Example with label\" aria-valuenow=\"25\"\r\n");
      out.write("                            aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width: 50%\">50%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- project section start -->\r\n");
      out.write("    <!-- <section class=\"teams\" id=\"teams\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <h2 class=\"title\">My Project</h2>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </section> -->\r\n");
      out.write("\r\n");
      out.write("     <!-- Project section start -->\r\n");
      out.write("    <section class=\"services\" id=\"project\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <h2 class=\"title\">My Projects</h2>\r\n");
      out.write("            <div class=\"serv-content\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-apple-alt\"></i>\r\n");
      out.write("                        <div class=\"text\">Delight Fruit's Shope</div>\r\n");
      out.write("                        <p><b>Technologies :</b> HTML, CSS, JavaScript.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-coins\"></i>\r\n");
      out.write("                        <div class=\"text\">CoinPressTurbo</div>\r\n");
      out.write("                        <p><b>Technologies :</b> Wordpress</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-candy-cane\"></i>\r\n");
      out.write("                        <div class=\"text\">Mango Sweets </div>\r\n");
      out.write("                        <p><b>Technologies :</b> Wordpress</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-user-tie\"></i>\r\n");
      out.write("                        <div class=\"text\">Siamaq Portal</div>\r\n");
      out.write("                        <p><b>Technologies :</b> JSP/HTML, CSS, JavaScript, jQuery, Bootstrap. </p>\r\n");
      out.write("                        <p><b>Database :</b> JAVA, MySQL.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-lightbulb\"></i>\r\n");
      out.write("                        <div class=\"text\">Morya Solar Shop</div><br>\r\n");
      out.write("                        <p><b>Technologies :</b>HTML, CSS, ASP.NET </p>\r\n");
      out.write("                        <p><b>Database :</b> MySQL.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <div class=\"text\">Portfolio</div>\r\n");
      out.write("                        <p><b>Technologies :</b>HTM / JSP, CSS, JavaScript </p>\r\n");
      out.write("                        <p><b>Database :</b> Java, MySQL.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- contact section start -->\r\n");
      out.write("    <section class=\"contact\" id=\"contact\">\r\n");
      out.write("        <div class=\"max-width\">\r\n");
      out.write("            <h2 class=\"title\">Contact me</h2>\r\n");
      out.write("            <div class=\"contact-content\">\r\n");
      out.write("                <div class=\"column left\">\r\n");
      out.write("                    <div class=\"text\">Get in Touch</div>\r\n");
      out.write("                    <p>If Anyone Want's To Meet Me Or Contact Me. Then Use Bellow Option Via Contact Me.\r\n");
      out.write("                        I Am Always Ready For Help. And Open For Job.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"icons\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <i class=\"fas fa-user\"></i>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <div class=\"head\">Name</div>\r\n");
      out.write("                                <div class=\"sub-title\">Purva Warke</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <div class=\"head\">Address</div>\r\n");
      out.write("                                <div class=\"sub-title\">Jalgaon, Maharashtra</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <div class=\"head\">Email</div>\r\n");
      out.write("                                <div class=\"sub-title\">warkepurva@gmail.com</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"column right\">\r\n");
      out.write("                    <div class=\"text\">Message me</div>\r\n");
      out.write("                    <form action=\"saveContact\" method=\"POST\">\r\n");
      out.write("                        <div class=\"fields\">\r\n");
      out.write("                            <div class=\"field name\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Name\" name=\"name\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field email\">\r\n");
      out.write("                                <input type=\"email\" placeholder=\"Email\" name=\"email\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"field\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Subject\" name=\"subject\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"field textarea\">\r\n");
      out.write("                            <textarea cols=\"30\" rows=\"10\" placeholder=\"Message..\" name=\"message\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"button-area\">\r\n");
      out.write("                            <button type=\"submit\">Send message</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- footer section start -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"fotercontainer\">\r\n");
      out.write("            <div class=\"socialicon\">\r\n");
      out.write("                <a href=\"https://www.linkedin.com/in/purva-warke-68ba71249\" class=\"social-link\" target=\"_blank\"><i\r\n");
      out.write("                        class=\"fa-brands fa-linkedin\"></i></a>\r\n");
      out.write("                <a href=\"https://github.com/PurvaWarke/\" class=\"social-link\" target=\"_blank\"><i\r\n");
      out.write("                        class=\"fa-brands fa-github\"></i></a>\r\n");
      out.write("                <a href=\"#\" class=\"social-link\" target=\"_blank\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\" class=\"social-link\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("                <a href=\"#\" class=\"social-link\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span>Created By <a href=\"#\">Purva Warke</a> | <span class=\"far fa-copyright\"></span> 2022 All rights\r\n");
      out.write("            reserved.</span>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
